package io.github.aomckin.lifehud.service;

import com.fasterxml.jackson.databind.node.*;import io.github.aomckin.lifehud.TestDataSupport;import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;import java.nio.file.*;import static org.assertj.core.api.Assertions.assertThat;
class AchievementSystemTest {
 @TempDir Path temp;TestDataSupport data;@BeforeEach void setup()throws Exception{data=new TestDataSupport(temp);data.baseline(50,0,0);}
 @Test void actionAndTotalCountsUnlockAtThreshold(){ArrayNode a=data.mapper.createArrayNode();a.add(item("action","action_count",2).put("target_action","学习"));a.add(item("total","total_action_count",3));data.json.write("achievements.json",a);var c=data.core();c.player().action_counts.put("学习",2);c.player().action_counts.put("健身",1);assertThat(c.achievements().checkAchievements()).extracting(x->x.get("id")).containsExactly("action","total");}
 @Test void multipleAchievementsUnlockAndRewardOnlyOnce(){ArrayNode a=data.mapper.createArrayNode();a.add(item("one","energy_reach",50).put("reward_coin",10));a.add(item("two","energy_reach",50).put("reward_exp",5));data.json.write("achievements.json",a);var c=data.core();var first=c.checkAchievements();assertThat(first).hasSize(2);assertThat(c.player().coin).isEqualTo(10);assertThat(c.player().exp).isZero();assertThat(c.checkAchievements()).isEmpty();assertThat(c.player().coin).isEqualTo(10);}
 @Test void taskComboUsesPersistentCompletedCounts(){ArrayNode req=data.mapper.createArrayNode();req.addObject().put("source","daily").put("task_id",data.json.read("tasks.json").path("tasks").get(0).path("id").asText()).put("count",1);req.addObject().put("source","special").put("task_id",data.json.read("special_tasks.json").path("tasks").get(0).path("id").asText()).put("count",1);ObjectNode achievement=item("combo","task_combo",0);achievement.set("requirements",req);data.json.write("achievements.json",data.mapper.createArrayNode().add(achievement));incrementFirst("tasks.json");incrementFirst("special_tasks.json");assertThat(data.core().achievements().checkAchievements()).extracting(x->x.get("id")).containsExactly("combo");}
 @Test void levelConditionUsesCumulativeExp(){data.json.write("achievements.json",data.mapper.createArrayNode().add(item("lv5","level",5)));ObjectNode s=data.save();s.put("exp",80);data.writeSave(s);assertThat(data.core().achievements().checkAchievements()).extracting(x->x.get("id")).containsExactly("lv5");}
 @Test void legacySaveMissingOptionalFieldsLoadsDefaults()throws Exception{Files.writeString(data.json.resolve("save.json"),"{\"energy\":42}");var p=data.players.load(50,180);assertThat(p.energy).isEqualTo(42);assertThat(p.exp).isZero();assertThat(p.special_task_slots).isEqualTo(1);assertThat(p.action_counts).isEmpty();assertThat(p.completed_timed_actions).isZero();}
 private ObjectNode item(String id,String type,int target){return data.mapper.createObjectNode().put("id",id).put("name",id).put("condition_type",type).put("target_value",target).put("reward_coin",0).put("reward_exp",0);}
 private void incrementFirst(String file){ObjectNode d=(ObjectNode)data.json.read(file);((ObjectNode)d.path("tasks").get(0)).put("completed_count",1).put("done",false);data.json.write(file,d);}
}
