package io.github.aomckin.lifehud.service;
import io.github.aomckin.lifehud.*;import io.github.aomckin.lifehud.domain.*;import io.github.aomckin.lifehud.repository.MediaRepository;import java.nio.file.Path;import java.time.Instant;import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;import static org.assertj.core.api.Assertions.*;
class MediaServiceTest{
 @TempDir Path temp;TestDataSupport data;V05TestWiring w;MediaService media;
 @BeforeEach void setup()throws Exception{data=new TestDataSupport(temp);data.baseline(100,0,0);w=V05TestWiring.create(data);media=new MediaService(new MediaRepository(data.json,data.mapper),new LifeFactRecorder(w.events));}
 @Test void animeSessionAdvancesProgressCompletesAndCreatesOneMediaFact(){Anime a=media.createAnime(new Anime(null,"葬送的芙莉莲",3,0,AnimeStatus.PLANNED,null,null,null,"","",null,null));Instant watched=Instant.parse("2026-08-20T12:00:00Z");AnimeWatchSession s=media.createAnimeSession(a.id(),new AnimeWatchSession(null,null,1,3,watched,72,"终章",null,null));assertThat(media.anime(a.id()).currentEpisode()).isEqualTo(3);assertThat(media.anime(a.id()).status()).isEqualTo(AnimeStatus.COMPLETED);assertThat(event(LifeEventType.ANIME_WATCHED)).satisfies(e->{assertThat(e.sourceType()).isEqualTo(LifeEventSourceType.MEDIA);assertThat(e.occurredAt()).isEqualTo(watched);assertThat(e.sourceId()).isEqualTo(s.id());});}
 @Test void editingAnimeSessionRewritesFactAndDeletingLeavesNoGhost(){Anime a=media.createAnime(new Anime(null,"测试番",12,0,AnimeStatus.WATCHING,null,null,null,"","",null,null));AnimeWatchSession s=media.createAnimeSession(a.id(),new AnimeWatchSession(null,null,1,1,Instant.parse("2026-08-20T12:00:00Z"),24,"",null,null));media.updateAnimeSession(s.id(),new AnimeWatchSession(null,null,1,2,Instant.parse("2026-08-21T12:00:00Z"),48,"两集",null,null));assertThat(event(LifeEventType.ANIME_WATCHED)).satisfies(e->{assertThat(e.version()).isEqualTo(2);assertThat(e.occurredAt()).isEqualTo(Instant.parse("2026-08-21T12:00:00Z"));});media.deleteAnimeSession(s.id());assertThat(w.events.all()).noneMatch(e->e.type()==LifeEventType.ANIME_WATCHED);}
 @Test void gameTotalAlwaysRecalculatesFromBaseAndSessions(){MediaGame g=media.createGame(new MediaGame(null,"异度神剑","Switch",MediaGameStatus.PLANNED,60,0,null,null,null,"","",null,null));MediaGameSession s=media.createGameSession(g.id(),new MediaGameSession(null,null,null,Instant.parse("2026-08-20T12:00:00Z"),30,"第一章","",null,null));assertThat(media.game(g.id()).totalPlayTimeMinutes()).isEqualTo(90);media.updateGameSession(s.id(),new MediaGameSession(null,null,null,Instant.parse("2026-08-20T13:00:00Z"),45,"第二章","",null,null));assertThat(media.game(g.id()).totalPlayTimeMinutes()).isEqualTo(105);media.deleteGameSession(s.id());assertThat(media.game(g.id()).totalPlayTimeMinutes()).isEqualTo(60);assertThat(w.events.all()).noneMatch(e->e.type()==LifeEventType.GAME_PLAYED);}
 @Test void invalidProgressAndDurationAreRejected(){assertThatThrownBy(()->media.createAnime(new Anime(null,"坏数据",12,13,AnimeStatus.WATCHING,null,null,null,"","",null,null))).hasMessageContaining("超过");MediaGame g=media.createGame(new MediaGame(null,"游戏","PC",MediaGameStatus.PLAYING,0,0,null,null,null,"","",null,null));assertThatThrownBy(()->media.createGameSession(g.id(),new MediaGameSession(null,null,null,Instant.now(),0,"","",null,null))).hasMessageContaining("大于 0");}
 @Test void archiveCreateUpdateAndRemoveAllBecomeMediaActivities(){MediaItem book=media.createItem(new MediaItem(null,MediaItemType.BOOK,"夜航西飞",MediaItemStatus.PLANNED,null,null,null,"","",null,null));media.updateItem(book.id(),new MediaItem(null,MediaItemType.BOOK,"夜航西飞",MediaItemStatus.IN_PROGRESS,9,null,null,"","开始阅读",null,null));media.deleteItem(book.id());assertThat(w.events.all()).extracting(e->e.type()).contains(LifeEventType.MEDIA_ADDED,LifeEventType.MEDIA_UPDATED,LifeEventType.MEDIA_REMOVED);assertThat(w.events.all()).allMatch(e->e.sourceType()==LifeEventSourceType.MEDIA&&"BOOK".equals(e.metadata().get("mediaType")));}
 @Test void archiveUpdateDescribesConcreteBeforeAndAfterValues(){Anime anime=media.createAnime(new Anime(null,"测试番",10,1,AnimeStatus.WATCHING,7,null,null,"","",null,null));media.updateAnime(anime.id(),new Anime(null,"测试番",10,3,AnimeStatus.PAUSED,9,null,null,"","看到关键剧情",null,null));LifeEvent update=event(LifeEventType.MEDIA_UPDATED);assertThat(update.description()).contains("观看进度 EP 1 → EP 3","状态 观看中 → 已暂停","评分 7/10 → 9/10","更新备注").doesNotContain("更新番剧档案");}
 private LifeEvent event(LifeEventType type){return w.events.all().stream().filter(e->e.type()==type).findFirst().orElseThrow();}
}
