package io.github.aomckin.lifehud.service;

import com.fasterxml.jackson.databind.node.ObjectNode;import io.github.aomckin.lifehud.TestDataSupport;import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;import java.nio.file.Path;import java.time.LocalDate;import java.util.Random;import static org.assertj.core.api.Assertions.assertThat;
class TaskManagerTest {
 @TempDir Path temp;TestDataSupport data;@BeforeEach void setup()throws Exception{data=new TestDataSupport(temp);}
 @Test void dailyFinishPersistsDoneAndCompletedCount(){var m=new DailyTaskManager(data.json,LocalDate::now,new Random(1));String id=m.tasks().getFirst().id;int before=m.tasks().getFirst().completedCount;int[] reward=m.finish(0);assertThat(reward[0]).isNotZero();var saved=find("tasks.json",id);assertThat(saved.path("done").asBoolean()).isTrue();assertThat(saved.path("completed_count").asInt()).isEqualTo(before+1);assertThat(m.finish(0)).containsExactly(0,0);}
 @Test void specialInvalidFinishReturnsZero(){var m=new SpecialTaskManager(data.json,1,LocalDate::now,new Random(1));assertThat(m.finish(-1)).containsExactly(0,0);assertThat(m.finish(999)).containsExactly(0,0);}
 @Test void increasingSpecialSlotsKeepsExistingActiveTask(){var m=new SpecialTaskManager(data.json,1,LocalDate::now,new Random(2));String existing=m.tasks().getFirst().id;m.setSlotCount(2);assertThat(m.tasks()).hasSize(2);assertThat(m.tasks()).extracting(t->t.id).contains(existing);}
 @Test void legacyActiveTaskIdMigrates(){ObjectNode d=(ObjectNode)data.json.read("special_tasks.json");String id=d.path("tasks").get(0).path("id").asText();d.remove("active_task_ids");d.put("active_task_id",id);data.json.write("special_tasks.json",d);var m=new SpecialTaskManager(data.json,1,LocalDate::now,new Random(1));assertThat(m.tasks().getFirst().id).isEqualTo(id);}
 @Test void dailyRedrawSelectsSixUnfinishedTasks(){var m=new DailyTaskManager(data.json,LocalDate::now,new Random(1));m.redraw();assertThat(m.tasks()).hasSize(6).noneMatch(t->t.done);}
 @Test void dailyRedrawReturnsAllRemainingTasksWhenFewerThanSixAreUnfinished(){var m=new DailyTaskManager(data.json,LocalDate::now,new Random(1));m.allTasks().forEach(t->t.done=true);m.allTasks().get(1).done=false;m.allTasks().get(6).done=false;m.redraw();assertThat(m.tasks()).extracting(t->t.id).containsExactlyInAnyOrder(m.allTasks().get(1).id,m.allTasks().get(6).id);assertThat(m.hasValidActiveTasks()).isTrue();}
 @Test void legacySpecialEnergyRewardsMigrateToExpOnlyOnce(){ObjectNode d=(ObjectNode)data.json.read("special_tasks.json");d.remove("reward_schema");((ObjectNode)d.path("tasks").get(0)).put("exp",25);data.json.write("special_tasks.json",d);var first=new SpecialTaskManager(data.json,2,LocalDate::now,new Random(1));assertThat(first.allTasks().getFirst().exp).isEqualTo(6);assertThat(data.json.read("special_tasks.json").path("reward_schema").asText()).isEqualTo("exp-v1");var second=new SpecialTaskManager(data.json,2,LocalDate::now,new Random(1));assertThat(second.allTasks().getFirst().exp).isEqualTo(6);}
 private com.fasterxml.jackson.databind.JsonNode find(String file,String id){for(var n:data.json.read(file).path("tasks"))if(id.equals(n.path("id").asText()))return n;throw new AssertionError(id);}
}
