package io.github.aomckin.lifehud.service;

import io.github.aomckin.lifehud.TestDataSupport;import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;import java.nio.file.Path;import static org.assertj.core.api.Assertions.assertThat;
class TitleSystemTest {
 @TempDir Path temp;TestDataSupport data;@BeforeEach void setup()throws Exception{data=new TestDataSupport(temp);data.baseline(50,0,500);}
 @Test void taskThresholdTitlesUnlock(){var c=data.core();c.dailyTasks().allTasks().getFirst().completedCount=1;assertThat(c.titles().checkTitles(c.dailyTasks().allTasks())).extracting(t->t.get("id")).contains("beginner");}
 @Test void objectActionTargetUnlocks(){var c=data.core();c.player().action_counts.put("学习",20);assertThat(c.titles().checkTitles(c.dailyTasks().allTasks())).extracting(t->t.get("id")).contains("magic_apprentice");}
 @Test void onlyEquippedTitleBonusAppliesAndSwitchingReplacesIt(){var c=data.core();c.player().unlocked_titles.add("archmage");c.player().unlocked_titles.add("magic_apprentice");assertThat(c.titles().equip("archmage")).isTrue();assertThat(c.titles().applyActionEnergyBonus("学习",10)).isEqualTo(13);assertThat(c.titles().equip("magic_apprentice")).isTrue();assertThat(c.titles().applyActionEnergyBonus("学习",10)).isEqualTo(11);assertThat(c.titles().applyActionEnergyBonus("健身",10)).isEqualTo(10);}
 @Test void negativeCostReductionDirectionIsCorrect(){var c=data.core();c.player().unlocked_titles.add("dimension_observer");c.titles().equip("dimension_observer");assertThat(c.titles().applyActionEnergyBonus("看番",-10)).isEqualTo(-9);assertThat(c.titles().applyActionEnergyBonus("打游戏",-10)).isEqualTo(-10);}
 @Test void timedAchievementAndShopConditionsUnlock(){var c=data.core();c.player().completed_timed_actions=20;c.player().unlocked_achievements.clear();for(int i=0;i<20;i++)c.player().unlocked_achievements.add("a"+i);c.player().shop_total_purchases.put("archmage_title",1);assertThat(c.titles().checkTitles(c.dailyTasks().allTasks())).extracting(t->t.get("id")).contains("focus_caster","achievement_collector","archmage");}
 @Test void lockedAndMissingTitlesCannotEquip(){var c=data.core();assertThat(c.titles().equip("archmage")).isFalse();c.player().unlocked_titles.add("missing");assertThat(c.titles().equip("missing")).isFalse();}
 @Test void taskExperienceBonusesMatchTheirSources(){var c=data.core();c.player().unlocked_titles.addAll(java.util.List.of("beginner","information_insulator","wind_traveler_title"));c.titles().equip("beginner");assertThat(c.titles().applyTaskExpBonus(5,"any","daily")).isEqualTo(6);c.titles().equip("information_insulator");assertThat(c.titles().applyTaskExpBonus(5,"any","special")).isEqualTo(6);assertThat(c.titles().applyTaskExpBonus(5,"any","daily")).isEqualTo(5);c.titles().equip("wind_traveler_title");assertThat(c.titles().applyTaskExpBonus(5,"walk_20_minutes","daily")).isEqualTo(6);assertThat(c.titles().applyTaskExpBonus(5,"other","daily")).isEqualTo(5);}
}
