spring:
  application:
    name: lifehud
  jackson:
    default-property-inclusion: always
  servlet:
    multipart:
      max-file-size: 64MB
      max-request-size: 128MB
server:
  address: 127.0.0.1
  port: 8025
