package io.github.aomckin.lifehud.core;

import com.fasterxml.jackson.databind.node.ObjectNode;
import io.github.aomckin.lifehud.TestDataSupport;
import io.github.aomckin.lifehud.dto.GameCommand;
import org.junit.jupiter.api.*;import org.junit.jupiter.api.io.TempDir;
import java.nio.file.Path;import java.util.*;
import static org.assertj.core.api.Assertions.assertThat;

class GameCoreTest {
 @TempDir Path temp;TestDataSupport data;
 @BeforeEach void setup()throws Exception{data=new TestDataSupport(temp);data.baseline(50,10,400);data.markAllUnlockablesUnlocked();}
 @Test void stateExposesUiViewModelWithoutShopEconomy(){var s=data.core().state();assertThat(s).containsKeys("window_title","window_size","energy_text","energy_value","energy_max","exp_text","level_text","title_text","logs","action_views","active_task_views","active_special_task_views","achievement_sections","title_views");assertThat(s).doesNotContainKeys("coin_text","shop_category_views");assertThat(s.get("energy_text")).isEqualTo("宅宅能量：50/180");assertThat((List<?>)s.get("action_views")).hasSize(6);}
 @Test void durationOptionsAreServerControlled(){var r=data.core().durationOptions("看番");assertThat(r.success()).isTrue();@SuppressWarnings("unchecked")var options=(List<Map<String,Object>>)r.events().getFirst().payload().get("options");assertThat(options).extracting("minutes").containsExactly(30,60,90);assertThat(data.core().durationOptions("不存在").success()).isFalse();}
 @Test void retiredActionCommandsAreRejectedWithoutMutatingState()throws Exception{var c=data.core();var r=c.execute(new GameCommand(GameCommands.COMPLETE_ACTION,data.mapper.readTree("{\"action_name\":\"学习\"}")));assertThat(r.success()).isFalse();var t=c.execute(new GameCommand(GameCommands.COMPLETE_TIMED_ACTION,data.mapper.readTree("{\"action_name\":\"看番\",\"option\":{\"minutes\":60,\"multiplier\":99,\"exp\":9999}}")));assertThat(t.success()).isFalse();assertThat(data.save().path("exp").asInt()).isEqualTo(10);assertThat(data.save().path("energy").asInt()).isEqualTo(50);}
 @Test void insufficientEnergyDoesNotMutateOrLog()throws Exception{ObjectNode s=data.save();s.put("energy",5);data.writeSave(s);var r=data.core().execute(new GameCommand(GameCommands.COMPLETE_ACTION,data.mapper.readTree("{\"action_name\":\"看番\"}")));assertThat(r.success()).isFalse();assertThat(data.save().path("energy").asInt()).isEqualTo(5);assertThat(data.json.exists("log.txt")).isFalse();assertThat(r.events().getFirst().type()).isEqualTo(GameEvents.ERROR);} @Test void unknownAndRetiredShopCommandsReturnOperationErrors()throws Exception{var c=data.core();assertThat(c.execute(new GameCommand("UNKNOWN",data.mapper.createObjectNode())).message()).isEqualTo("未知指令");assertThat(c.execute(new GameCommand(GameCommands.BUY_SHOP_ITEM,data.mapper.readTree("{\"item_id\":\"missing\"}"))).message()).contains("已停用商店");}
 @Test void abandonedActionOnlyWritesLog()throws Exception{var r=data.core().execute(new GameCommand(GameCommands.LOG_ABANDONED_ACTION,data.mapper.readTree("{\"action_name\":\"学习\",\"elapsed_minutes\":3}")));assertThat(r.success()).isTrue();assertThat(data.logs.recent().getLast()).contains("放弃学习","3分钟");assertThat(data.save().path("energy").asInt()).isEqualTo(50);}
 @Test void dailyTaskRewardsAndProgressionAreAppliedOnlyOnce()throws Exception{var c=data.core();var task=c.dailyTasks().tasks().getFirst();int beforeEnergy=c.player().energy,beforeExp=c.player().exp;var payload=data.mapper.readTree("{\"index\":0}");var first=c.execute(new GameCommand(GameCommands.COMPLETE_DAILY_TASK,payload));assertThat(first.success()).isTrue();assertThat(c.player().energy).isEqualTo(Math.min(c.player().maxEnergy,beforeEnergy+task.reward));assertThat(c.player().exp).isEqualTo(beforeExp);assertThat(c.player().done_task_count).isEqualTo(1);assertThat(first.events().getFirst().type()).isEqualTo(GameEvents.TASK_COMPLETE);int settledExp=c.player().exp,settledEnergy=c.player().energy;c.execute(new GameCommand(GameCommands.COMPLETE_DAILY_TASK,payload));assertThat(c.player().exp).isEqualTo(settledExp);assertThat(c.player().energy).isEqualTo(settledEnergy);assertThat(c.player().done_task_count).isEqualTo(1);}
 @Test void specialTaskGrantsExpWithoutEnergyOrCurrency()throws Exception{var c=data.core();var task=c.specialTasks().tasks().getFirst();int coin=c.player().coin,energy=c.player().energy,exp=c.player().exp;var result=c.execute(new GameCommand(GameCommands.COMPLETE_SPECIAL_TASK,data.mapper.readTree("{\"index\":0}")));assertThat(result.success()).isTrue();assertThat(c.player().coin).isEqualTo(coin);assertThat(c.player().energy).isEqualTo(energy);assertThat(c.player().exp).isEqualTo(exp+task.exp);assertThat(c.player().done_special_task_count).isEqualTo(1);var saved=data.json.read("special_tasks.json").path("tasks");assertThat(saved.findValuesAsText("id")).contains(task.id);assertThat(saved.get(saved.findValuesAsText("id").indexOf(task.id)).path("done").asBoolean()).isTrue();}
 @Test void retiredShopCommandDoesNotMutateState()throws Exception{var c=data.core();var result=c.execute(new GameCommand(GameCommands.BUY_SHOP_ITEM,data.mapper.readTree("{\"item_id\":\"special_task_slot\"}")));assertThat(result.success()).isFalse();assertThat(c.player().special_task_slots).isEqualTo(1);assertThat(data.save().path("shop_total_purchases").isEmpty()).isTrue();}
 @Test void savedStateIsRestoredByANewCoreInstance()throws Exception{var first=data.core();first.execute(new GameCommand(GameCommands.COMPLETE_DAILY_TASK,data.mapper.readTree("{\"index\":0}")));var restored=data.core();assertThat(restored.player().energy).isEqualTo(first.player().energy);assertThat(restored.player().done_task_count).isEqualTo(1);assertThat(restored.player().exp).isEqualTo(10);assertThat(restored.state().get("energy_value")).isEqualTo(first.player().energy);}
 @Test void legacyDoubleExpPurchaseNoLongerChangesTaskGrowth()throws Exception{ObjectNode save=data.save();save.put("daily_double_exp_date",java.time.LocalDate.now().toString());data.writeSave(save);var c=data.core();int before=c.player().exp;c.execute(new GameCommand(GameCommands.COMPLETE_DAILY_TASK,data.mapper.readTree("{\"index\":0}")));assertThat(c.player().exp).isEqualTo(before);}
}
