package io.github.aomckin.lifehud;

import io.github.aomckin.lifehud.core.GameCommandFacade;import io.github.aomckin.lifehud.domain.Player;import io.github.aomckin.lifehud.service.PlayerService;import org.junit.jupiter.api.Test;import java.lang.reflect.Method;import java.nio.file.*;import static org.assertj.core.api.Assertions.assertThat;
class ArchitectureTest {
 @Test void allJavaCodeUsesRequiredRootPackage()throws Exception{try(var files=Files.walk(Path.of("src"))){for(Path p:files.filter(x->x.toString().endsWith(".java")).toList()){String text=Files.readString(p);assertThat(text).as(p.toString()).contains("package io.github.aomckin.lifehud");}}}
 @Test void playerEntityHasNoBusinessMethods(){assertThat(Player.class.getDeclaredMethods()).extracting(Method::getName).allMatch(n->n.startsWith("lambda$")||n.equals("equals")||n.equals("hashCode")||n.equals("toString"));}
 @Test void playerServiceHasNoRepositoryDependency(){assertThat(PlayerService.class.getDeclaredFields()).isEmpty();}
 @Test void webUiUsesShellAndDedicatedGrowthPage()throws Exception{String shell=Files.readString(Path.of("src/main/resources/static/v0.2.html"));String routes=Files.readString(Path.of("src/main/resources/static/modules/navigation.js"));String growth=Files.readString(Path.of("src/main/resources/static/pages/growth.js"));assertThat(shell).contains("Life HUD v1.0.0","growth.css","direction.css","media.css");assertThat(routes).contains("/dashboard","/focus","/growth","/media");assertThat(growth).contains("Achievements","Milestones","Titles").doesNotContain("Coin","Shop");}
 @Test void wideCanvasPagesSpanAllTwelveColumns()throws Exception{String shell=Files.readString(Path.of("src/main/resources/static/styles/shell.css"));assertThat(shell).contains("#page > .life-page","#page > .timeline-page","grid-column: 1 / -1");}
 @Test void businessServicesDoNotDependOnGlobalGameCore()throws Exception{try(var files=Files.walk(Path.of("src/main/java/io/github/aomckin/lifehud/service"))){for(Path p:files.filter(x->x.toString().endsWith(".java")).toList()){String text=Files.readString(p);assertThat(text).as(p.toString()).doesNotContain("GameCore");}}
 }
 @Test void commandFacadeOwnsCommandRouting(){assertThat(GameCommandFacade.class.isAnnotationPresent(org.springframework.stereotype.Component.class)).isTrue();}
 @Test void mediaUsesChineseStatusesAndImageInputsAcceptClipboardPaste()throws Exception{String media=Files.readString(Path.of("src/main/resources/static/pages/media.js"));String paste=Files.readString(Path.of("src/main/resources/static/modules/image-paste.js"));String app=Files.readString(Path.of("src/main/resources/static/app-v02.js"));assertThat(media).contains("PLANNED:\"计划中\"","DROPPED:\"已放弃\"","statusLabels[s]");assertThat(paste).contains("clipboardData","DataTransfer","input.dispatchEvent");assertThat(app).contains("enableImagePaste()");}
 @Test void playlistMaximumSizeRequiresOneThousandPlaysAndSongCopyHasNoUndefinedLabels()throws Exception{String playlist=Files.readString(Path.of("src/main/resources/static/pages/now-playlist.js"));String copy=Files.readString(Path.of("src/main/resources/static/content/copy.js"));assertThat(playlist).contains("playCount >= 1000","c.titleLabel || \"歌名\"","c.cancel || \"取消\"").doesNotContain("playCount >= 50) return \"featured\"");assertThat(copy).contains("titleLabel: \"歌名\"","cancel: \"取消\"");}
 @Test void genericJsonStoreHasNoDomainSpecificKnowledge()throws Exception{String text=Files.readString(Path.of("src/main/java/io/github/aomckin/lifehud/repository/JsonFileStore.java"));assertThat(text).doesNotContain("Player").doesNotContain("Achievement").doesNotContain("Task").doesNotContain("Log");}
}
