package io.github.aomckin.lifehud.controller;
import io.github.aomckin.lifehud.domain.*;import io.github.aomckin.lifehud.service.MediaService;import java.util.List;import org.springframework.http.HttpStatus;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/media") public final class MediaController{
 private final MediaService media;public MediaController(MediaService media){this.media=media;}
 @GetMapping("/anime") public List<Anime> anime(){return media.anime();}@GetMapping("/anime/{id}") public Anime anime(@PathVariable String id){return media.anime(id);}@PostMapping("/anime") @ResponseStatus(HttpStatus.CREATED) public Anime createAnime(@RequestBody Anime r){return media.createAnime(r);}@PutMapping("/anime/{id}") public Anime updateAnime(@PathVariable String id,@RequestBody Anime r){return media.updateAnime(id,r);}@DeleteMapping("/anime/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void deleteAnime(@PathVariable String id){media.deleteAnime(id);}
 @GetMapping("/anime/{id}/sessions") public List<AnimeWatchSession> animeSessions(@PathVariable String id){return media.animeSessions(id);}@PostMapping("/anime/{id}/sessions") @ResponseStatus(HttpStatus.CREATED) public AnimeWatchSession createAnimeSession(@PathVariable String id,@RequestBody AnimeWatchSession r){return media.createAnimeSession(id,r);}@PutMapping("/anime-sessions/{id}") public AnimeWatchSession updateAnimeSession(@PathVariable String id,@RequestBody AnimeWatchSession r){return media.updateAnimeSession(id,r);}@DeleteMapping("/anime-sessions/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void deleteAnimeSession(@PathVariable String id){media.deleteAnimeSession(id);}
 @GetMapping("/games") public List<MediaGame> games(){return media.games();}@GetMapping("/games/{id}") public MediaGame game(@PathVariable String id){return media.game(id);}@PostMapping("/games") @ResponseStatus(HttpStatus.CREATED) public MediaGame createGame(@RequestBody MediaGame r){return media.createGame(r);}@PutMapping("/games/{id}") public MediaGame updateGame(@PathVariable String id,@RequestBody MediaGame r){return media.updateGame(id,r);}@DeleteMapping("/games/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void deleteGame(@PathVariable String id){media.deleteGame(id);}
 @GetMapping("/games/{id}/sessions") public List<MediaGameSession> gameSessions(@PathVariable String id){return media.gameSessions(id);}@PostMapping("/games/{id}/sessions") @ResponseStatus(HttpStatus.CREATED) public MediaGameSession createGameSession(@PathVariable String id,@RequestBody MediaGameSession r){return media.createGameSession(id,r);}@PutMapping("/game-sessions/{id}") public MediaGameSession updateGameSession(@PathVariable String id,@RequestBody MediaGameSession r){return media.updateGameSession(id,r);}@DeleteMapping("/game-sessions/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void deleteGameSession(@PathVariable String id){media.deleteGameSession(id);}
 @GetMapping("/items") public List<MediaItem> items(@RequestParam(required=false) MediaItemType type){return media.items(type);}@GetMapping("/items/{id}") public MediaItem item(@PathVariable String id){return media.item(id);}@PostMapping("/items") @ResponseStatus(HttpStatus.CREATED) public MediaItem createItem(@RequestBody MediaItem r){return media.createItem(r);}@PutMapping("/items/{id}") public MediaItem updateItem(@PathVariable String id,@RequestBody MediaItem r){return media.updateItem(id,r);}@DeleteMapping("/items/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void deleteItem(@PathVariable String id){media.deleteItem(id);}
}
