package io.github.aomckin.lifehud.domain;

public enum GrowthMetric {
    IRON_FOCUS_COUNT, POMODORO_FOCUS_COUNT, FOCUS_COUNT, EFFECTIVE_FOCUS_MINUTES,
    MAX_EFFECTIVE_FOCUS_MINUTES, CROSS_MIDNIGHT_FOCUS_COUNT, TASK_COUNT,
    LIFE_EVENT_COUNT, MILESTONE_COUNT, LEVEL, ENERGY,
    DREAM_CREATED_COUNT, DREAM_MILESTONE_COMPLETED_COUNT, DREAM_COMPLETED_COUNT,
    RITUAL_COMPLETED_COUNT, SLEEP_RECORDED_COUNT, MEAL_RECORDED_COUNT,
    CHECK_IN_RECORDED_COUNT, EXERCISE_RECORDED_COUNT, LIFE_RECORD_DAY_STREAK,
    ANIME_SESSION_COUNT, ANIME_COMPLETED_COUNT, GAME_SESSION_COUNT, GAME_COMPLETED_COUNT,
    DAILY_DISTINCT_SOURCE_MAX
}
