package io.github.aomckin.lifehud.domain;

public enum GrowthMetric {
    IRON_FOCUS_COUNT, POMODORO_FOCUS_COUNT, FOCUS_COUNT, EFFECTIVE_FOCUS_MINUTES,
    MAX_EFFECTIVE_FOCUS_MINUTES, CROSS_MIDNIGHT_FOCUS_COUNT, TASK_COUNT,
    LIFE_EVENT_COUNT, MILESTONE_COUNT, LEVEL, ENERGY
}
