package io.github.aomckin.lifehud.domain;

/** Stable event vocabulary shared by current and future Life HUD modules. */
public enum LifeEventType {
    TASK_COMPLETED,
    FOCUS_STARTED,
    FOCUS_PAUSED,
    FOCUS_RESUMED,
    FOCUS_SEGMENT_CHANGED,
    FOCUS_FINISHED,
    LEVEL_UP,
    ACHIEVEMENT_UNLOCKED,
    MILESTONE_CREATED,
    MILESTONE_UPDATED,
    MILESTONE_DELETED,
    TITLE_UNLOCKED,
    TITLE_EQUIPPED,
    RITUAL_COMPLETED,
    ENTERTAINMENT_RECORDED,
    ENTERTAINMENT_UPDATED,
    ENTERTAINMENT_DELETED,
    ENERGY_SPENT,
    ENERGY_CHANGED,
    JOURNAL_WRITTEN,
    MANUAL_EVENT
}
