package io.github.aomckin.lifehud.service;

import io.github.aomckin.lifehud.domain.*;
import io.github.aomckin.lifehud.repository.MediaRepository;
import java.time.*;
import java.time.temporal.ChronoUnit;
import java.util.*;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

@Service
public final class MediaService {
    private final MediaRepository repo; private final LifeFactRecorder facts;
    public MediaService(MediaRepository repo,LifeFactRecorder facts){this.repo=repo;this.facts=facts;}
    public List<Anime> anime(){return repo.anime().stream().sorted(Comparator.comparing(Anime::updatedAt).reversed()).toList();}
    public Anime anime(String id){return repo.anime().stream().filter(v->v.id().equals(id)).findFirst().orElseThrow(()->missing("番剧"));}
    public synchronized Anime createAnime(Anime r){Anime v=saveAnime(null,r);recordArchiveActivity(LifeEventType.MEDIA_ADDED,"ANIME",v.id(),v.title(),"加入番剧档案",v.createdAt());return v;}
    public synchronized Anime updateAnime(String id,Anime r){Anime old=anime(id);Anime v=saveAnime(id,r);recordArchiveActivity(LifeEventType.MEDIA_UPDATED,"ANIME",v.id(),v.title(),animeChanges(old,v),v.updatedAt());return v;}
    private Anime saveAnime(String id,Anime r){String title=title(r==null?null:r.title());int total=nonNegative(r==null?0:r.totalEpisodes(),"总集数");int current=nonNegative(r==null?0:r.currentEpisode(),"当前集数");if(total>0&&current>total)throw bad("当前集数不能超过总集数");Integer score=score(r==null?null:r.score());Instant now=Instant.now();Anime old=id==null?null:anime(id);AnimeStatus status=r==null||r.status()==null?AnimeStatus.PLANNED:r.status();Instant finished=r==null?null:r.finishedAt();if(status==AnimeStatus.COMPLETED&&finished==null)finished=now;Anime v=new Anime(id==null?UUID.randomUUID().toString():id,title,total,current,status,score,r==null?null:r.startedAt(),finished,clean(r==null?null:r.coverImage()),clean(r==null?null:r.note()),old==null?now:old.createdAt(),now);repo.saveAnime(v);return v;}
    public synchronized void deleteAnime(String id){Anime old=anime(id);for(AnimeWatchSession s:animeSessions(id)){repo.deleteAnimeSession(s.id());facts.recordDeleted(LifeEventType.ANIME_WATCHED,s.id());}repo.deleteAnime(id);recordArchiveActivity(LifeEventType.MEDIA_REMOVED,"ANIME",old.id(),old.title(),"移除番剧档案",Instant.now());}
    public List<AnimeWatchSession> animeSessions(String animeId){anime(animeId);return repo.animeSessions().stream().filter(v->v.animeId().equals(animeId)).sorted(Comparator.comparing(AnimeWatchSession::watchedAt).reversed()).toList();}
    public synchronized AnimeWatchSession createAnimeSession(String animeId,AnimeWatchSession r){anime(animeId);return saveAnimeSession(null,animeId,r);}
    public synchronized AnimeWatchSession updateAnimeSession(String id,AnimeWatchSession r){AnimeWatchSession old=repo.animeSessions().stream().filter(v->v.id().equals(id)).findFirst().orElseThrow(()->missing("观看记录"));return saveAnimeSession(id,old.animeId(),r);}
    private AnimeWatchSession saveAnimeSession(String id,String animeId,AnimeWatchSession r){Anime a=anime(animeId);int start=r==null?0:r.episodeStart(),end=r==null?0:r.episodeEnd();if(start<1||end<start)throw bad("观看集数无效");if(a.totalEpisodes()>0&&end>a.totalEpisodes())throw bad("观看集数不能超过总集数");if(r!=null&&r.durationMinutes()!=null&&r.durationMinutes()<=0)throw bad("观看时长必须大于 0");Instant now=Instant.now(),watched=r==null||r.watchedAt()==null?now:r.watchedAt();AnimeWatchSession old=id==null?null:repo.animeSessions().stream().filter(v->v.id().equals(id)).findFirst().orElse(null);AnimeWatchSession v=new AnimeWatchSession(id==null?UUID.randomUUID().toString():id,animeId,start,end,watched,r==null?null:r.durationMinutes(),clean(r==null?null:r.note()),old==null?now:old.createdAt(),now);repo.saveAnimeSession(v);if(end>a.currentEpisode()){AnimeStatus status=a.status()==AnimeStatus.PLANNED?AnimeStatus.WATCHING:a.status();Instant finished=a.finishedAt();if(a.totalEpisodes()>0&&end>=a.totalEpisodes()){status=AnimeStatus.COMPLETED;if(finished==null)finished=watched;}repo.saveAnime(new Anime(a.id(),a.title(),a.totalEpisodes(),end,status,a.score(),a.startedAt()==null?watched:a.startedAt(),finished,a.coverImage(),a.note(),a.createdAt(),now));}syncAnimeFact(v,id==null);return v;}
    public synchronized void deleteAnimeSession(String id){AnimeWatchSession s=repo.animeSessions().stream().filter(v->v.id().equals(id)).findFirst().orElseThrow(()->missing("观看记录"));repo.deleteAnimeSession(id);facts.recordDeleted(LifeEventType.ANIME_WATCHED,s.id());}
    private void syncAnimeFact(AnimeWatchSession s,boolean create){Anime a=anime(s.animeId());String content="观看 EP%02d - EP%02d%s%s".formatted(s.episodeStart(),s.episodeEnd(),s.durationMinutes()==null?"":" · "+s.durationMinutes()+" min",s.note().isBlank()?"":" · "+s.note());Map<String,Object> meta=new HashMap<>();meta.put("mediaType","ANIME");meta.put("mediaId",a.id());meta.put("sessionId",s.id());meta.put("episodeStart",s.episodeStart());meta.put("episodeEnd",s.episodeEnd());if(s.durationMinutes()!=null)meta.put("durationMinutes",s.durationMinutes());if(create)facts.recordCreated(LifeEventType.ANIME_WATCHED,"media",s.id(),"《"+a.title()+"》",content,s.watchedAt(),List.of("media","anime"),meta);else facts.recordUpdated(LifeEventType.ANIME_WATCHED,"media",s.id(),"《"+a.title()+"》",content,s.watchedAt(),List.of("media","anime"),meta);}

    public List<MediaGame> games(){return repo.games().stream().sorted(Comparator.comparing(MediaGame::updatedAt).reversed()).toList();}
    public MediaGame game(String id){return repo.games().stream().filter(v->v.id().equals(id)).findFirst().orElseThrow(()->missing("游戏"));}
    public synchronized MediaGame createGame(MediaGame r){MediaGame v=saveGame(null,r);recordArchiveActivity(LifeEventType.MEDIA_ADDED,"GAME",v.id(),v.title(),"加入游戏档案",v.createdAt());return v;}
    public synchronized MediaGame updateGame(String id,MediaGame r){MediaGame old=game(id);MediaGame v=saveGame(id,r);recordArchiveActivity(LifeEventType.MEDIA_UPDATED,"GAME",v.id(),v.title(),gameChanges(old,v),v.updatedAt());return v;}
    private MediaGame saveGame(String id,MediaGame r){String title=title(r==null?null:r.title());int base=nonNegative(r==null?0:r.basePlayTimeMinutes(),"历史时长");Integer score=score(r==null?null:r.score());Instant now=Instant.now();MediaGame old=id==null?null:game(id);int sessions=id==null?0:repo.gameSessions().stream().filter(v->v.gameId().equals(id)).mapToInt(MediaGameSession::durationMinutes).sum();MediaGameStatus status=r==null||r.status()==null?MediaGameStatus.PLANNED:r.status();Instant finished=r==null?null:r.finishedAt();if(status==MediaGameStatus.COMPLETED&&finished==null)finished=now;MediaGame v=new MediaGame(id==null?UUID.randomUUID().toString():id,title,clean(r==null?null:r.platform()),status,base,base+sessions,r==null?null:r.startedAt(),finished,score,clean(r==null?null:r.coverImage()),clean(r==null?null:r.note()),old==null?now:old.createdAt(),now);repo.saveGame(v);return v;}
    public synchronized void deleteGame(String id){MediaGame old=game(id);for(MediaGameSession s:gameSessions(id)){repo.deleteGameSession(s.id());facts.recordDeleted(LifeEventType.GAME_PLAYED,s.id());}repo.deleteGame(id);recordArchiveActivity(LifeEventType.MEDIA_REMOVED,"GAME",old.id(),old.title(),"移除游戏档案",Instant.now());}
    public List<MediaGameSession> gameSessions(String gameId){game(gameId);return repo.gameSessions().stream().filter(v->v.gameId().equals(gameId)).sorted(Comparator.comparing(MediaGameSession::endTime).reversed()).toList();}
    public synchronized MediaGameSession createGameSession(String gameId,MediaGameSession r){game(gameId);return saveGameSession(null,gameId,r);}
    public synchronized MediaGameSession updateGameSession(String id,MediaGameSession r){MediaGameSession old=repo.gameSessions().stream().filter(v->v.id().equals(id)).findFirst().orElseThrow(()->missing("游玩记录"));return saveGameSession(id,old.gameId(),r);}
    private MediaGameSession saveGameSession(String id,String gameId,MediaGameSession r){MediaGame g=game(gameId);Instant start=r==null?null:r.startTime(),end=r==null?null:r.endTime();int duration=r==null?0:r.durationMinutes();if(start!=null&&end!=null){if(end.isBefore(start))throw bad("结束时间不能早于开始时间");long calculated=ChronoUnit.MINUTES.between(start,end);if(calculated<=0)throw bad("游玩时长必须大于 0");if(duration>0&&Math.abs(duration-calculated)>1)throw bad("填写时长与开始结束时间不一致");duration=(int)calculated;}if(duration<=0)throw bad("游玩时长必须大于 0");if(end==null)end=Instant.now();if(start==null)start=end.minus(duration,ChronoUnit.MINUTES);Instant now=Instant.now();MediaGameSession old=id==null?null:repo.gameSessions().stream().filter(v->v.id().equals(id)).findFirst().orElse(null);MediaGameSession v=new MediaGameSession(id==null?UUID.randomUUID().toString():id,gameId,start,end,duration,clean(r==null?null:r.progress()),clean(r==null?null:r.note()),old==null?now:old.createdAt(),now);repo.saveGameSession(v);recalculateGame(g.id(),now);syncGameFact(v,id==null);return v;}
    public synchronized void deleteGameSession(String id){MediaGameSession s=repo.gameSessions().stream().filter(v->v.id().equals(id)).findFirst().orElseThrow(()->missing("游玩记录"));repo.deleteGameSession(id);facts.recordDeleted(LifeEventType.GAME_PLAYED,s.id());recalculateGame(s.gameId(),Instant.now());}
    private void recalculateGame(String id,Instant now){MediaGame g=game(id);int total=g.basePlayTimeMinutes()+repo.gameSessions().stream().filter(v->v.gameId().equals(id)).mapToInt(MediaGameSession::durationMinutes).sum();MediaGameStatus status=g.status()==MediaGameStatus.PLANNED?MediaGameStatus.PLAYING:g.status();repo.saveGame(new MediaGame(g.id(),g.title(),g.platform(),status,g.basePlayTimeMinutes(),total,g.startedAt(),g.finishedAt(),g.score(),g.coverImage(),g.note(),g.createdAt(),now));}
    private void syncGameFact(MediaGameSession s,boolean create){MediaGame g=game(s.gameId());String detail=!s.progress().isBlank()?s.progress():s.note();String content="游玩 "+s.durationMinutes()+" min"+(detail.isBlank()?"":" · "+detail);Map<String,Object> meta=new HashMap<>();meta.put("mediaType","GAME");meta.put("mediaId",g.id());meta.put("sessionId",s.id());meta.put("durationMinutes",s.durationMinutes());meta.put("platform",g.platform());meta.put("progress",s.progress());if(create)facts.recordCreated(LifeEventType.GAME_PLAYED,"media",s.id(),"《"+g.title()+"》",content,s.endTime(),List.of("media","game"),meta);else facts.recordUpdated(LifeEventType.GAME_PLAYED,"media",s.id(),"《"+g.title()+"》",content,s.endTime(),List.of("media","game"),meta);}

    public List<MediaItem> items(MediaItemType type){return repo.items().stream().filter(v->type==null||v.type()==type).sorted(Comparator.comparing(MediaItem::updatedAt).reversed()).toList();}
    public MediaItem item(String id){return repo.items().stream().filter(v->v.id().equals(id)).findFirst().orElseThrow(()->missing("作品"));}
    public synchronized MediaItem createItem(MediaItem r){MediaItem v=saveItem(null,r);recordArchiveActivity(LifeEventType.MEDIA_ADDED,v.type().name(),v.id(),v.title(),"加入"+itemTypeLabel(v.type())+"档案",v.createdAt());return v;}
    public synchronized MediaItem updateItem(String id,MediaItem r){MediaItem old=item(id);MediaItem v=saveItem(id,r);recordArchiveActivity(LifeEventType.MEDIA_UPDATED,v.type().name(),v.id(),v.title(),itemChanges(old,v),v.updatedAt());return v;}
    private MediaItem saveItem(String id,MediaItem r){String title=title(r==null?null:r.title());if(r==null||r.type()==null)throw bad("作品类型不能为空");Instant now=Instant.now();MediaItem old=id==null?null:item(id);MediaItemStatus status=r.status()==null?MediaItemStatus.PLANNED:r.status();Instant finished=r.finishedAt();if(status==MediaItemStatus.COMPLETED&&finished==null)finished=now;MediaItem v=new MediaItem(id==null?UUID.randomUUID().toString():id,r.type(),title,status,score(r.score()),r.startedAt(),finished,clean(r.coverImage()),clean(r.note()),old==null?now:old.createdAt(),now);repo.saveItem(v);return v;}
    public synchronized void deleteItem(String id){MediaItem old=item(id);repo.deleteItem(id);recordArchiveActivity(LifeEventType.MEDIA_REMOVED,old.type().name(),old.id(),old.title(),"移除"+itemTypeLabel(old.type())+"档案",Instant.now());}
    private void recordArchiveActivity(LifeEventType eventType,String mediaType,String mediaId,String title,String content,Instant time){facts.recordActivity(eventType,"media","《"+title+"》",content,time,List.of("media",mediaType.toLowerCase()),Map.of("mediaType",mediaType,"mediaId",mediaId,"action",eventType.name()));}
    private String itemTypeLabel(MediaItemType type){return switch(type){case BOOK->"书籍";case MANGA->"漫画";case MOVIE->"电影";case OTHER->"作品";};}
    private String animeChanges(Anime old,Anime value){List<String> changes=new ArrayList<>();changed(changes,"观看进度",episode(old.currentEpisode()),episode(value.currentEpisode()));changed(changes,"总集数",String.valueOf(old.totalEpisodes()),String.valueOf(value.totalEpisodes()));changed(changes,"状态",animeStatus(old.status()),animeStatus(value.status()));changed(changes,"评分",scoreText(old.score()),scoreText(value.score()));changed(changes,"标题",old.title(),value.title());if(!Objects.equals(old.coverImage(),value.coverImage()))changes.add("更换封面");if(!Objects.equals(old.note(),value.note()))changes.add("更新备注");return changes.isEmpty()?"保存番剧档案":String.join(" · ",changes);}
    private String gameChanges(MediaGame old,MediaGame value){List<String> changes=new ArrayList<>();changed(changes,"状态",gameStatus(old.status()),gameStatus(value.status()));changed(changes,"平台",blankText(old.platform()),blankText(value.platform()));changed(changes,"历史时长",minutes(old.basePlayTimeMinutes()),minutes(value.basePlayTimeMinutes()));changed(changes,"评分",scoreText(old.score()),scoreText(value.score()));changed(changes,"标题",old.title(),value.title());if(!Objects.equals(old.coverImage(),value.coverImage()))changes.add("更换封面");if(!Objects.equals(old.note(),value.note()))changes.add("更新备注");return changes.isEmpty()?"保存游戏档案":String.join(" · ",changes);}
    private String itemChanges(MediaItem old,MediaItem value){List<String> changes=new ArrayList<>();changed(changes,"状态",itemStatus(old.status()),itemStatus(value.status()));changed(changes,"评分",scoreText(old.score()),scoreText(value.score()));changed(changes,"标题",old.title(),value.title());if(!Objects.equals(old.coverImage(),value.coverImage()))changes.add("更换封面");if(!Objects.equals(old.note(),value.note()))changes.add("更新备注");return changes.isEmpty()?"保存"+itemTypeLabel(value.type())+"档案":String.join(" · ",changes);}
    private void changed(List<String> changes,String label,String before,String after){if(!Objects.equals(before,after))changes.add(label+" "+before+" → "+after);}
    private String episode(int value){return value<=0?"尚未观看":"EP "+value;}
    private String minutes(int value){return value+" min";}
    private String scoreText(Integer value){return value==null?"未评分":value+"/10";}
    private String blankText(String value){return value==null||value.isBlank()?"未填写":value;}
    private String animeStatus(AnimeStatus value){return switch(value){case PLANNED->"计划中";case WATCHING->"观看中";case PAUSED->"已暂停";case COMPLETED->"已完成";case DROPPED->"已放弃";};}
    private String gameStatus(MediaGameStatus value){return switch(value){case PLANNED->"计划中";case PLAYING->"游玩中";case PAUSED->"已暂停";case COMPLETED->"已完成";case DROPPED->"已放弃";};}
    private String itemStatus(MediaItemStatus value){return switch(value){case PLANNED->"计划中";case IN_PROGRESS->"进行中";case PAUSED->"已暂停";case COMPLETED->"已完成";case DROPPED->"已放弃";};}
    private String title(String v){String s=clean(v);if(s.isBlank())throw bad("标题不能为空");return s;}
    private String clean(String v){return v==null?"":v.trim();} private int nonNegative(int v,String label){if(v<0)throw bad(label+"不能为负数");return v;} private Integer score(Integer v){if(v!=null&&(v<0||v>10))throw bad("评分应在 0 到 10 之间");return v;}
    private ResponseStatusException bad(String m){return new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}private ResponseStatusException missing(String n){return new ResponseStatusException(HttpStatus.NOT_FOUND,n+"不存在");}
}
