package io.github.aomckin.lifehud.core;

public final class GameCommands {
    private GameCommands(){}
    public static final String COMPLETE_ACTION="COMPLETE_ACTION", COMPLETE_TIMED_ACTION="COMPLETE_TIMED_ACTION", COMPLETE_DAILY_TASK="COMPLETE_DAILY_TASK", COMPLETE_SPECIAL_TASK="COMPLETE_SPECIAL_TASK", BUY_SHOP_ITEM="BUY_SHOP_ITEM", EQUIP_TITLE="EQUIP_TITLE", REFRESH_DAILY_TASKS="REFRESH_DAILY_TASKS", INITIALIZE_PROGRESSION="INITIALIZE_PROGRESSION", LOG_ABANDONED_ACTION="LOG_ABANDONED_ACTION";
}
