package io.github.aomckin.lifehud.core;

public final class GameEvents {
    private GameEvents(){}
    public static final String LEVEL_UP="LEVEL_UP", ACHIEVEMENT_UNLOCK="ACHIEVEMENT_UNLOCK", TITLE_UNLOCK="TITLE_UNLOCK", ACTION_COMPLETE="ACTION_COMPLETE", TASK_COMPLETE="TASK_COMPLETE", SHOP_PURCHASE="SHOP_PURCHASE", ACTION_DURATION_OPTIONS="ACTION_DURATION_OPTIONS", ERROR="ERROR";
}
